### ISSUE TITLE
Search and highlight 

### ISSUE THREAD

**Issue by rclarkburns** [lthurston/quiet#8]
Adding a search flag to either the list or dump command would be most helpful. 

Something akin to:  `quiet list -s 'me_search_term'` which would replace having to do `cat ~/.ssh/config | grep -C5 --color=auto 'me_search_term'`

**Comment by lthurston** [comment]
No highlighting yet, but try this out:

$ quiet find searchterm1 searchterm2

**Comment by lthurston** [comment]
Ok, highlighting now works, although for some reason I have to add spaces around the highlighted section for it to work. I'ma leave the issue open until I resolve this.

**Comment by lthurston** [comment]
Remove the spaces and it works fine now. I must have been smoking crack.
